import { useState } from 'react'
import { type MugParameters } from '../App'
import { extractClosedShapes, filterShapesBySize } from '../utils/shapeAnalysis'
import { generateInfillForShapes } from '../utils/infillGenerator'

interface GCodeGeneratorProps {
  svgPaths: any[]
  parameters: MugParameters
  viewBox?: { width: number, height: number }
}

function GCodeGenerator({ svgPaths, parameters, viewBox }: GCodeGeneratorProps) {
  const [gcode, setGcode] = useState<string>('')
  const [isGenerating, setIsGenerating] = useState(false)
  const [isSending, setIsSending] = useState(false)
  const [status, setStatus] = useState<string>('')

  const generateGCode = () => {
    console.log('generateGCode called, paths:', svgPaths.length)
    
    if (svgPaths.length === 0) {
      setStatus('Please load an SVG file first')
      return
    }

    setIsGenerating(true)
    setStatus('Generating GCODE...')

    try {
      const lines: string[] = []
      
      // GCODE header
      lines.push('; MugBot GCODE - Generated by MugBot UI')
      lines.push('; Date: ' + new Date().toISOString())
      lines.push('; X Range: ' + parameters.xRange + 'mm')
      lines.push('; Y Range: ' + parameters.yRange + 'mm')
      lines.push('; Extrusion Rate: ' + parameters.extrusionRate)
      lines.push('; Z Position: 0mm (fixed)')
      lines.push('')
      lines.push('G21 ; Set units to millimeters')
      lines.push('G90 ; Absolute positioning')
      lines.push('M83 ; Relative extrusion mode')
      lines.push('G92 E0 ; Reset extruder position')
      lines.push('M221 S' + Math.round(parameters.extrusionRate * 100) + ' ; Set extrusion multiplier to ' + Math.round(parameters.extrusionRate * 100) + '%')
      lines.push('')
      lines.push('; Move to start position')
      lines.push('G0 Z0 F3000 ; Set Z to 0')
      lines.push('G0 X0 Y0 F3000 ; Move to origin')
      lines.push('')

      // Process each SVG path
      svgPaths.forEach((pathData, pathIndex) => {
        lines.push('; Path ' + (pathIndex + 1))
        
        const rawPoints = parseSvgPathToGCode(pathData.d, parameters, pathData.transform)
        const pathPoints = simplifyPoints(rawPoints)
        lines.push('; Raw points: ' + rawPoints.length + ', Simplified: ' + pathPoints.length)
        
        if (pathPoints.length > 0) {
          // Move to start without extrusion
          lines.push('G0 X' + pathPoints[0].x.toFixed(3) + ' Y' + pathPoints[0].y.toFixed(3) + ' F3000')
          
          // Draw the path
          for (let i = 1; i < pathPoints.length; i++) {
            const point = pathPoints[i]
            const prevPoint = pathPoints[i - 1]
            
            // Calculate distance for extrusion
            const dx = point.x - prevPoint.x
            const dy = point.y - prevPoint.y
            const distance = Math.sqrt(dx * dx + dy * dy)
            const extrusion = distance * parameters.extrusionRate * 0.1
            
            lines.push('G1 X' + point.x.toFixed(3) + ' Y' + point.y.toFixed(3) + ' E' + extrusion.toFixed(5) + ' F1500')
          }
        }
        
        lines.push('')
      })

      // Generate infill if enabled
      if (parameters.infill.enabled) {
        console.log('Infill is ENABLED, generating infill...')
        console.log('Infill parameters:', parameters.infill)
        lines.push('; Infill generation')
        lines.push('; Min Size: ' + parameters.infill.minSize + 'mm')
        lines.push('; Line Spacing: ' + parameters.infill.lineSpacing + 'mm')
        lines.push('; Angle: ' + parameters.infill.angle + '°')
        lines.push('')
        
        try {
          // Create SVG content from paths for shape extraction
          const svgContent = createSVGFromPaths(svgPaths)
          console.log('Created SVG content for infill analysis')
          
          // Extract closed shapes
          const allShapes = extractClosedShapes(svgContent)
          console.log('Extracted closed shapes:', allShapes.length)
          console.log('Closed shapes details:', allShapes)
          lines.push('; Found ' + allShapes.length + ' closed shapes')
          
          // Filter by minimum size
          const filteredShapes = filterShapesBySize(allShapes, parameters.infill.minSize)
          lines.push('; ' + filteredShapes.length + ' shapes meet minimum size requirement')
          lines.push('')
          
          // Generate infill for each shape
          const infillMap = generateInfillForShapes(filteredShapes, parameters.infill)
          
          let totalInfillLines = 0
          infillMap.forEach((infillLines, shapeId) => {
            if (infillLines.length > 0) {
              lines.push('; Infill for ' + shapeId + ' (' + infillLines.length + ' segments)')
              totalInfillLines += infillLines.length
              
              infillLines.forEach((line, lineIndex) => {
                // Convert infill line to mug coordinates
                const start = convertInfillPointToMugCoords(line.start, parameters)
                const end = convertInfillPointToMugCoords(line.end, parameters)
                
                // Move to start
                if (lineIndex === 0 || !isPointClose(infillLines[lineIndex - 1].end, line.start)) {
                  lines.push('G0 X' + start.x.toFixed(3) + ' Y' + start.y.toFixed(3) + ' F3000')
                }
                
                // Draw line
                const dx = end.x - start.x
                const dy = end.y - start.y
                const distance = Math.sqrt(dx * dx + dy * dy)
                const extrusion = distance * parameters.extrusionRate * 0.1
                
                lines.push('G1 X' + end.x.toFixed(3) + ' Y' + end.y.toFixed(3) + ' E' + extrusion.toFixed(5) + ' F1500')
              })
              
              lines.push('')
            }
          })
          
          lines.push('; Total infill segments: ' + totalInfillLines)
          lines.push('')
        } catch (error) {
          lines.push('; Error generating infill: ' + (error as Error).message)
          console.error('Infill generation error:', error)
        }
      }

      // GCODE footer
      lines.push('; End of print')
      lines.push('G0 Z5 F1000 ; Lift nozzle')
      lines.push('G0 X0 Y0 F3000 ; Return to origin')
      lines.push('M400 ; Wait for moves to finish')
      lines.push('M84 ; Disable motors')

      const gcodeContent = lines.join('\n')
      setGcode(gcodeContent)
      setStatus('GCODE generated successfully (' + lines.length + ' lines)')
    } catch (error) {
      setStatus('Error generating GCODE: ' + (error as Error).message)
    } finally {
      setIsGenerating(false)
    }
  }

  // Parse transform helpers to match visualization behavior
  const parseTransform = (transformStr: string | null): { a: number, b: number, c: number, d: number, e: number, f: number } | null => {
    if (!transformStr) return null
    const matrixMatch = transformStr.match(/matrix\(([-\d.,\s]+)\)/)
    if (matrixMatch) {
      const values = matrixMatch[1].split(/[\s,]+/).map(parseFloat)
      if (values.length === 6) {
        return { a: values[0], b: values[1], c: values[2], d: values[3], e: values[4], f: values[5] }
      }
    }
    const translateMatch = transformStr.match(/translate\(([-\d.,\s]+)\)/)
    if (translateMatch) {
      const values = translateMatch[1].split(/[\s,]+/).map(parseFloat)
      const tx = values[0] || 0
      const ty = values[1] || 0
      return { a: 1, b: 0, c: 0, d: 1, e: tx, f: ty }
    }
    const scaleMatch = transformStr.match(/scale\(([-\d.,\s]+)\)/)
    if (scaleMatch) {
      const values = scaleMatch[1].split(/[\s,]+/).map(parseFloat)
      const sx = values[0] || 1
      const sy = values[1] || sx
      return { a: sx, b: 0, c: 0, d: sy, e: 0, f: 0 }
    }
    return null
  }

  const applyTransform = (x: number, y: number, matrix: { a: number, b: number, c: number, d: number, e: number, f: number }): [number, number] => {
    const newX = matrix.a * x + matrix.c * y + matrix.e
    const newY = matrix.b * x + matrix.d * y + matrix.f
    return [newX, newY]
  }

  const parseSvgPathToGCode = (pathD: string, params: MugParameters, transformStr?: string | null): Array<{x: number, y: number}> => {
    const points: Array<{x: number, y: number}> = []
    const commands = pathD.match(/[MmLlHhVvCcSsQqTtAaZz][^MmLlHhVvCcSsQqTtAaZz]*/g) || []
    
    let currentX = 0
    let currentY = 0
    let startX = 0
    let startY = 0

    // Use viewBox dimensions to align with visualization
    const svgWidth = viewBox?.width || 280
    const svgHeight = viewBox?.height || 80
    const minX = 0
    const minY = 0

    const transform = parseTransform(transformStr || null)

    // Convert path commands to points
    commands.forEach(cmd => {
      const type = cmd[0]
      const isRelative = type === type.toLowerCase()
      const coords = cmd.slice(1).trim().split(/[\s,]+/).map(parseFloat).filter(n => !isNaN(n))

      switch (type.toUpperCase()) {
        case 'M':
          if (coords.length >= 2) {
            currentX = isRelative ? currentX + coords[0] : coords[0]
            currentY = isRelative ? currentY + coords[1] : coords[1]
            startX = currentX
            startY = currentY
            const [tx, ty] = transform ? applyTransform(currentX, currentY, transform) : [currentX, currentY]
            points.push(convertToMugCoords(tx, ty, minX, minY, svgWidth, svgHeight, params))
          }
          break

        case 'C': // Cubic Bezier curve
          for (let i = 0; i < coords.length; i += 6) {
            if (coords[i] !== undefined && coords[i + 1] !== undefined && 
                coords[i + 2] !== undefined && coords[i + 3] !== undefined &&
                coords[i + 4] !== undefined && coords[i + 5] !== undefined) {
              const cp1X = isRelative ? currentX + coords[i] : coords[i]
              const cp1Y = isRelative ? currentY + coords[i + 1] : coords[i + 1]
              const cp2X = isRelative ? currentX + coords[i + 2] : coords[i + 2]
              const cp2Y = isRelative ? currentY + coords[i + 3] : coords[i + 3]
              const newX = isRelative ? currentX + coords[i + 4] : coords[i + 4]
              const newY = isRelative ? currentY + coords[i + 5] : coords[i + 5]
              
              const steps = 10
              for (let step = 1; step <= steps; step++) {
                const t = step / steps
                const mt = 1 - t
                const x = mt * mt * mt * currentX + 3 * mt * mt * t * cp1X + 3 * mt * t * t * cp2X + t * t * t * newX
                const y = mt * mt * mt * currentY + 3 * mt * mt * t * cp1Y + 3 * mt * t * t * cp2Y + t * t * t * newY
                const [tx, ty] = transform ? applyTransform(x, y, transform) : [x, y]
                points.push(convertToMugCoords(tx, ty, minX, minY, svgWidth, svgHeight, params))
              }
              
              currentX = newX
              currentY = newY
            }
          }
          break

         case 'L':
          for (let i = 0; i < coords.length; i += 2) {
            if (coords[i] !== undefined && coords[i + 1] !== undefined) {
              const newX = isRelative ? currentX + coords[i] : coords[i]
              const newY = isRelative ? currentY + coords[i + 1] : coords[i + 1]
              
               // Straight line: add only the endpoint to avoid micro-steps
               const [tx, ty] = transform ? applyTransform(newX, newY, transform) : [newX, newY]
               points.push(convertToMugCoords(tx, ty, minX, minY, svgWidth, svgHeight, params))
              
              currentX = newX
              currentY = newY
            }
          }
          break

        case 'H':
          for (let i = 0; i < coords.length; i++) {
            if (coords[i] !== undefined) {
              const newX = isRelative ? currentX + coords[i] : coords[i]
               const [tx, ty] = transform ? applyTransform(newX, currentY, transform) : [newX, currentY]
               points.push(convertToMugCoords(tx, ty, minX, minY, svgWidth, svgHeight, params))
              currentX = newX
            }
          }
          break

        case 'V':
          for (let i = 0; i < coords.length; i++) {
            if (coords[i] !== undefined) {
              const newY = isRelative ? currentY + coords[i] : coords[i]
               const [tx, ty] = transform ? applyTransform(currentX, newY, transform) : [currentX, newY]
               points.push(convertToMugCoords(tx, ty, minX, minY, svgWidth, svgHeight, params))
              currentY = newY
            }
          }
          break

        case 'Q': // Quadratic Bezier curve
          for (let i = 0; i < coords.length; i += 4) {
            if (coords[i] !== undefined && coords[i + 1] !== undefined && 
                coords[i + 2] !== undefined && coords[i + 3] !== undefined) {
              const cpX = isRelative ? currentX + coords[i] : coords[i]
              const cpY = isRelative ? currentY + coords[i + 1] : coords[i + 1]
              const newX = isRelative ? currentX + coords[i + 2] : coords[i + 2]
              const newY = isRelative ? currentY + coords[i + 3] : coords[i + 3]
              
              // Approximate quadratic bezier with line segments
              const steps = 5
              for (let step = 1; step <= steps; step++) {
                const t = step / steps
                const x = (1 - t) * (1 - t) * currentX + 2 * (1 - t) * t * cpX + t * t * newX
                const y = (1 - t) * (1 - t) * currentY + 2 * (1 - t) * t * cpY + t * t * newY
                const [tx, ty] = transform ? applyTransform(x, y, transform) : [x, y]
                points.push(convertToMugCoords(tx, ty, minX, minY, svgWidth, svgHeight, params))
              }
              
              currentX = newX
              currentY = newY
            }
          }
          break

         case 'Z':
          if (startX !== currentX || startY !== currentY) {
            const [tx, ty] = transform ? applyTransform(startX, startY, transform) : [startX, startY]
            points.push(convertToMugCoords(tx, ty, minX, minY, svgWidth, svgHeight, params))
          }
          currentX = startX
          currentY = startY
          break
      }
    })

    return points
  }

  // Simplify: remove tiny moves and merge collinear points
  const simplifyPoints = (pts: Array<{x: number, y: number}>): Array<{x: number, y: number}> => {
    if (pts.length <= 2) return pts
    const epsilon = 0.01 // mm
    const out: Array<{x: number, y: number}> = [pts[0]]
    for (let i = 1; i < pts.length; i++) {
      const prev = out[out.length - 1]
      const cur = pts[i]
      const dx = cur.x - prev.x
      const dy = cur.y - prev.y
      const dist = Math.sqrt(dx*dx + dy*dy)
      if (dist < epsilon) continue
      // Attempt collinearity merge with previous segment
      if (out.length >= 2) {
        const a = out[out.length - 2]
        const b = prev
        const c = cur
        const abx = b.x - a.x, aby = b.y - a.y
        const bcx = c.x - b.x, bcy = c.y - b.y
        const cross = Math.abs(abx * bcy - aby * bcx)
        const abLen = Math.sqrt(abx*abx + aby*aby)
        const bcLen = Math.sqrt(bcx*bcx + bcy*bcy)
        if (abLen > 0 && bcLen > 0 && cross / (abLen * bcLen) < 1e-6) {
          // Collinear: replace prev with cur
          out[out.length - 1] = cur
          continue
        }
      }
      out.push(cur)
    }
    return out
  }

  const convertToMugCoords = (
    svgX: number,
    svgY: number,
    minX: number,
    minY: number,
    svgWidth: number,
    svgHeight: number,
    params: MugParameters
  ): {x: number, y: number} => {
    // Convert SVG coordinates from their origin (minX, minY) to mm from origin
    // SVG units are assumed to be in mm
    // Invert X for left-to-right rendering (negate to flip horizontally)
    const xInMm = (svgWidth - (svgX - minX)) + params.xOffset
    // Flip Y coordinate (SVG Y increases downward, mug Y increases upward)
    const yInMm = (svgHeight - (svgY - minY)) + params.yOffset

    // Use actual mm values directly
    // X is rotation around mug (0 to xRange in mm)
    const x = xInMm
    // Y is vertical height (0 to yRange in mm)
    const y = yInMm

    return { x, y }
  }

  const convertInfillPointToMugCoords = (
    point: { x: number, y: number },
    params: MugParameters
  ): { x: number, y: number } => {
    // Match visualization's coordinate mapping (flip X and Y relative to viewBox)
    const svgWidth = viewBox?.width || 280
    const svgHeight = viewBox?.height || 80
    const minX = 0
    const minY = 0
    const xInMm = (svgWidth - (point.x - minX)) + params.xOffset
    const yInMm = (svgHeight - (point.y - minY)) + params.yOffset
    return { x: xInMm, y: yInMm }
  }

  const createSVGFromPaths = (paths: any[]): string => {
    const pathElements = paths.map((p, i) => {
      const transformAttr = p.transform ? ` transform="${p.transform}"` : ''
      return `<path id="path-${i}" d="${p.d}"${transformAttr} />`
    }).join('\n')
    
    return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg">
${pathElements}
</svg>`
  }

  const isPointClose = (
    p1: { x: number, y: number },
    p2: { x: number, y: number },
    tolerance: number = 0.01
  ): boolean => {
    const dx = p2.x - p1.x
    const dy = p2.y - p1.y
    return Math.sqrt(dx * dx + dy * dy) < tolerance
  }

  const downloadGCode = () => {
    if (!gcode) return

    const blob = new Blob([gcode], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'mugbot_' + new Date().getTime() + '.gcode'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    
    setStatus('GCODE file downloaded')
  }

  const sendToDuet = async () => {
    if (!gcode) {
      setStatus('Generate GCODE first')
      return
    }

    if (!parameters.duetIp) {
      setStatus('Please enter Duet IP address')
      return
    }

    setIsSending(true)
    setStatus('Uploading to Duet 2...')

    try {
      // Create form data
      const formData = new FormData()
      const blob = new Blob([gcode], { type: 'text/plain' })
      const filename = 'mugbot_' + new Date().getTime() + '.gcode'
      formData.append('file', blob, filename)

      // Upload to Duet 2 using RRF3 API
      const uploadUrl = `http://${parameters.duetIp}/rr_upload?name=0:/gcodes/${filename}`
      
      await fetch(uploadUrl, {
        method: 'POST',
        body: formData,
        mode: 'no-cors' // Note: This may require CORS configuration on Duet
      })

      // Since we're using no-cors, we can't read the response
      // Assume success if no error was thrown
      setStatus('GCODE uploaded successfully to Duet 2')
      
      // Optionally, you could also start the print job:
      // await fetch(`http://${parameters.duetIp}/rr_gcode?gcode=M32 "${filename}"`, { mode: 'no-cors' })
      
    } catch (error) {
      setStatus('Error uploading to Duet: ' + (error as Error).message)
      console.error('Upload error:', error)
    } finally {
      setIsSending(false)
    }
  }

  return (
    <div>
      <div className="d-grid gap-2 mb-3">
        <button 
          className="btn btn-primary"
          onClick={generateGCode}
          disabled={isGenerating || svgPaths.length === 0}
        >
          {isGenerating ? 'Generating...' : 'Generate GCODE'}
        </button>

        <button 
          className="btn btn-success"
          onClick={downloadGCode}
          disabled={!gcode}
        >
          Download GCODE
        </button>

        <button 
          className="btn btn-warning"
          onClick={sendToDuet}
          disabled={!gcode || isSending}
        >
          {isSending ? 'Uploading...' : 'Send to Duet 2'}
        </button>
      </div>

      {status && (
        <div className={`alert ${status.includes('Error') ? 'alert-danger' : 'alert-info'} small mb-3`}>
          {status}
        </div>
      )}

      {gcode && (
        <div>
          <label className="form-label small fw-bold">GCODE Preview:</label>
          <textarea 
            className="form-control font-monospace small"
            rows={10}
            value={gcode}
            readOnly
            style={{ fontSize: '0.75rem' }}
          />
          <small className="text-muted d-block mt-1">
            {gcode.split('\n').length} lines, {(gcode.length / 1024).toFixed(1)} KB
          </small>
        </div>
      )}
    </div>
  )
}

export default GCodeGenerator
